name: Test Main
on:
  push:
    branches:
      - main
jobs:
  test-main:
    if: github.repository == 'hack-dance/island-ai' && github.ref == 'refs/heads/main'
    name: run-tests
    runs-on: ubuntu-latest
    environment: OPENAI
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANYSCALE_API_KEY: ${{ secrets.ANYSCALE_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTRHOPIC_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      AZURE_OPENAI_API_KEY: ${{secrets.AZURE_OPENAI_API_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: bun i

      - run: bun run build
      - run: bun run type-check
      - run: bun run lint
      - run: bun test --timeout=25000
